// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0TyOoWLbwYuViCDh00OTYRx8TBCzntKc',
    appId: '1:41420743420:web:a48ab2f299af6212ba2d79',
    messagingSenderId: '41420743420',
    projectId: 'cotizo-ccf4d',
    authDomain: 'cotizo-ccf4d.firebaseapp.com',
    storageBucket: 'cotizo-ccf4d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ6CnW7ec0Q8jtRJt0ilw0FR-9VNyd1N4',
    appId: '1:41420743420:android:10ede34dd6238161ba2d79',
    messagingSenderId: '41420743420',
    projectId: 'cotizo-ccf4d',
    storageBucket: 'cotizo-ccf4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF5qUxK71T21aJL1lMrHZJLB-wyisR6eg',
    appId: '1:41420743420:ios:67b5dfb64d89e102ba2d79',
    messagingSenderId: '41420743420',
    projectId: 'cotizo-ccf4d',
    storageBucket: 'cotizo-ccf4d.appspot.com',
    androidClientId: '41420743420-c07t96kdm8pfk7vm73cfibonht09gfb8.apps.googleusercontent.com',
    iosClientId: '41420743420-n0fgg8dj80gahsh6gdn92neibketvth9.apps.googleusercontent.com',
    iosBundleId: 'com.autoparnet.cotizo',
  );
}
