// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD19Loon44gM-HiPOkWreCCie8OvnuSl-E',
    appId: '1:647320495318:web:75a4c0d63784eb70251577',
    messagingSenderId: '647320495318',
    projectId: 'autoparnet-c1d0b',
    authDomain: 'autoparnet-c1d0b.firebaseapp.com',
    storageBucket: 'autoparnet-c1d0b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdngd4-WCZd_W9K6UOiDYr4RMTmU2mHpg',
    appId: '1:647320495318:android:68e6ed97cd14678e251577',
    messagingSenderId: '647320495318',
    projectId: 'autoparnet-c1d0b',
    storageBucket: 'autoparnet-c1d0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWl8_X6WGz6rlKpUo-pwdulfyfU7f4m-A',
    appId: '1:647320495318:ios:3d87ddced4d85dce251577',
    messagingSenderId: '647320495318',
    projectId: 'autoparnet-c1d0b',
    storageBucket: 'autoparnet-c1d0b.appspot.com',
    iosClientId: '647320495318-aeurvqcjr18uokf9opr6mo264c0t4aif.apps.googleusercontent.com',
    iosBundleId: 'com.autoparnet.cotizo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWl8_X6WGz6rlKpUo-pwdulfyfU7f4m-A',
    appId: '1:647320495318:ios:3d87ddced4d85dce251577',
    messagingSenderId: '647320495318',
    projectId: 'autoparnet-c1d0b',
    storageBucket: 'autoparnet-c1d0b.appspot.com',
    iosClientId: '647320495318-aeurvqcjr18uokf9opr6mo264c0t4aif.apps.googleusercontent.com',
    iosBundleId: 'com.autoparnet.cotizo',
  );
}
